### ISSUE TITLE
Conversion failed for column `REGION` with type object

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#1307]
```
Traceback (most recent call last):
  File "/tmp/tmp_k7qwhvg/webviz_app.py", line 147, in <module>
    plugin = webviz_config.plugins.VolumetricAnalysis(webviz_settings=webviz_settings, **{'ensembles': ['sens'], 'volfiles': {'geogrid': '..._fmu.csv'}, 'csvfile_vol': None, 'csvfile_parameters': None, 'volfolder': 'share/results/volumes', 'non_net_facies': None, 'fipfile': None, 'drop_failed_realizations': True})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/webviz_subsurface/plugins/_volumetric_analysis/volumetric_analysis.py", line 186, in __init__
    volumes_table = extract_volframe_from_tableprovider(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/webviz_subsurface/_models/inplace_volumes_model.py", line 411, in extract_volframe_from_tableprovider
    table_provider_set = create_csvfile_providerset_from_paths(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/webviz_subsurface/_utils/ensemble_table_provider_set_factory.py", line 28, in create_csvfile_providerset_from_paths
    provider_dict[name] = provider_factory.create_from_per_realization_csv_file(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_factory.py", line 165, in create_from_per_realization_csv_file
    EnsembleTableProviderImplArrow.write_backing_store_from_ensemble_dataframe(
  File ".../site-packages/webviz_subsurface/_providers/ensemble_table_provider/ensemble_table_provider_impl_arrow.py", line 147, in write_backing_store_from_ensemble_dataframe
    table = pa.Table.from_pandas(ensemble_df, preserve_index=False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4623, in pyarrow.lib.Table.from_pandas
  File ".../site-packages/pyarrow/pandas_compat.py", line 629, in dataframe_to_arrays
    arrays[i] = maybe_fut.result()
                ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../site-packages/pyarrow/pandas_compat.py", line 603, in convert_column
    raise e
  File ".../site-packages/pyarrow/pandas_compat.py", line 597, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 358, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 85, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 92, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'int' object", 'Conversion failed for column REGION with type object')
```

**Comment by HansKallekleiv** [comment]
This occurs if there is a mix of dtypes (string / int) between different realizations., maybe due to fault/region uncertainty resulting in different names between realizations.

Support for this will most likely cause other issues in visualization. 

Closing. Will not fix.
