### ISSUE TITLE
Flask caching SwigPyObject

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#219]
Using `webviz-subsurface-testdata` (and with `webviz-config` after the `logging`-`WARNING` PR), I get the following error:
```
   ERROR: 	Exception possibly due to cache backend.
Traceback (most recent call last):
  File "[...]/lib/python3.7/site-packages/flask_caching/__init__.py", line 841, in decorated_function
    timeout=decorated_function.cache_timeout,
  File "[...]/lib/python3.7/site-packages/flask_caching/backends/simple.py", line 76, in set
    pickle.dumps(value, pickle.HIGHEST_PROTOCOL),
TypeError: can't pickle SwigPyObject objects
```

**Comment by anders-kiaer** [comment]
The dash app continues with its life, so appears not to be a problem. But looks like something is `cached` (which is not possible to `cache`). Maybe something from `xtgeo` @HansKallekleiv

**Comment by anders-kiaer** [comment]
Might be possible to fix now after upstream change https://github.com/equinor/xtgeo/pull/300.

**Comment by anders-kiaer** [comment]
This issue is resolved and verified with recent release of upstream dependency `xtgeo` (`xtgeo>=2.7`).
