### ISSUE TITLE
RFTPlotter crashes when filters in tab "RFT misfit per observations" gives has no match

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface#840]
While applying the filters in the RFT misfit per observation tab of the RFTPlotter I have many times experience this Error (see full traceback below). I have not been able to understand exactly what triggers it, but I have to restart the app when it happens.

```
ERROR:webviz_app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RFT_NAME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/generic.py", line 3576, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'RFT_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/webviz_subsurface/plugins/_rft_plotter/rft_plotter.py", line 824, in _errorplot
    return update_errorplot(df, self.enscolors)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/webviz_subsurface/plugins/_rft_plotter/_errorplot_figure.py", line 14, in update_errorplot
    axis=1,
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/frame.py", line 3121, in _set_item
    NDFrame._set_item(self, key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/generic.py", line 3579, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/managers.py", line 1198, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 2744, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 2400, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 28, placement implies 1
ERROR:webviz_app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'RFT_NAME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/generic.py", line 3576, in _set_item
    loc = self._info_axis.get_loc(key)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'RFT_NAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/dash/dash.py", line 1336, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/dash/_callback.py", line 151, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/webviz_subsurface/plugins/_rft_plotter/rft_plotter.py", line 824, in _errorplot
    return update_errorplot(df, self.enscolors)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib/python3.6/site-packages/webviz_subsurface/plugins/_rft_plotter/_errorplot_figure.py", line 14, in update_errorplot
    axis=1,
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/frame.py", line 3121, in _set_item
    NDFrame._set_item(self, key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/generic.py", line 3579, in _set_item
    self._mgr.insert(len(self._info_axis), key, value)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/managers.py", line 1198, in insert
    block = make_block(values=value, ndim=self.ndim, placement=slice(loc, loc + 1))
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 2744, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 2400, in __init__
    super().__init__(values, ndim=ndim, placement=placement)
  File "/prog/res/komodo/2021.10.04-py36-rhel7/root/lib64/python3.6/site-packages/pandas/core/internals/blocks.py", line 131, in __init__
    f"Wrong number of items passed {len(self.values)}, "
ValueError: Wrong number of items passed 28, placement implies 1
```

**Comment by lindjoha** [comment]
I have now figured out that this happens when the filters applied gives no matching RFTs. F.ex when you have selected a zone, but then selects a well that doesn't have a RFT in that zone.
